version: '3.9'

services:
  db:
    image: my-mysql:8.0
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    cap_add:
      - SYS_NICE
    networks:
      - network
    environment:
      - "MYSQL_ROOT_PASSWORD=asd;flkjasd;lfkjas;dlkfj"
      - "MYSQL_USER=javid"
      - "MYSQL_PASSWORD=javid_9999"
      - "MYSQL_DATABASE=recordings"   
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - network

  web:
    image: album:latest
    ports:
      - "8070:8070"
    networks:
      - network
    volumes:
      - ".env:/app/.env"
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"
    env_file:
      - .env

networks:
  network:
    name: album_network
    driver: bridge
    
volumes:
  db_vol: