version: '3.9'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    networks:
      - network
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
    volumes:
      - db_vol:/var/lib/mysql

  web:
    image: album:latest
    ports:
      - "8070:8070"
    networks:
      - network
    volumes:
      - ".env:/app/.env"
    depends_on:
      - db
    links:
      - "db:database"
    env_file:
      - .env

networks:
  network:
    name: album_network
    driver: bridge
    
volumes:
  db_vol: