version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=asd;flkjasd;lfkjas;dlkfj"
      - "MYSQL_USER=javid"
      - "MYSQL_PASSWORD=javid_9999"
      - "MYSQL_DATABASE=recordings"   
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env

networks:
  network:
    name: mysql_network
    driver: bridge
    
volumes:
  db_vol: