version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: on-failure
    networks:
      - network
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
    volumes:
      - db_vol:/var/lib/mysql
  web:
    image: myalbum:v5
    restart: on-failure
    ports:
      - "8080:80"
    networks:
      - network
    volumes:
      - ".env:/app/.env"
    depends_on:
      - db
    links:
      - "db:database"

networks:
  network:
    name: album_network
    driver: bridge
    
volumes:
  db_vol: