basePath: /
host: localhost:8070
info:
  contact:
    email: api@swagger.io
    name: API Support
    url: http://www.swagger.io/api
  description: This is a sample server for save Albums in mysql database
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Gin Album API
  version: "1.0"
paths: {}
swagger: "2.0"
